name: Build and Deploy ARC3N

on:
 workflow_dispatch:
 issues:
    types: [opened, reopened, edited, closed, deleted]
 push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Clone Font Awesome Overwrites âœŒï¸
        uses: actions/checkout@v2
        with:
          repository: abunai-dev/UncertaintySourceArchive-overwrites
          path: UncertaintySourceArchive/fonts
          token: ${{ secrets.OVERWRITES_READONLY_TOKEN }}
      
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install, Fetch and Build ğŸ”§
        working-directory: UncertaintySourceArchive
        run: |
          npm install
          npm run fetch-uncertainties
          npm run build

      - name: Deploy ğŸš€
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          path: UncertaintySourceArchive/dist/
          remote_path: /home/${{ secrets.USERNAME }}/html/${{ vars.TARGET }}
          remote_host: ${{ secrets.SERVER }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.PRIVATE_KEY }}
